// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glceadbwjanmymdvdrna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsY2VhZGJ3amFubXltZHZkcm5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzI1OTEsImV4cCI6MjA2OTgwODU5MX0.5rPIgswUu_47PB2_KsQju2TPGALlJhAqN88sJVY_ig4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});